version: '4'
services:
  client-frontend:
    image: ghcr.io/bizinmitya/front-react-avito:v1.13
    ports:
      - "3000:3000"
    depends_on:
      - client-backend

  client-backend:
    image: m7only/backend:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8181"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/graduate-work

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_DB: graduate-work
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
  pgadmin-data: